[workspace]
channels = ["conda-forge", "anybody"]
name = "anypytools-tutorial"
platforms = ["win-64"]

[tasks]
start = {cmd="jupyter lab"}


[dependencies]
python = ">=3.12,<3.13"
jupyter = ">=1.1.1,<2"
anybodycon = ">=8.1.3,<9"
anypytools = ">=1.17.1,<2"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.0,<3"
seaborn = ">=0.13.2,<0.14"

